version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    # build: ./flask_app
    ports:
      - 5000:5000
    command: gunicorn -w 1 --log-level=debug  -b 0.0.0.0:5000 app:app
    volumes:
      - .:/root

  nginx:
    container_name: nginx
    restart: always
    # build: ./nginx
    ports:
      - 80:80
    depends_on:
      - flask_app
    volumes:
      - ./flask_app/static:/etc/nginx/static
